### PR TITLE
Make screenhole links open in same tab

### PR DESCRIPTION
**Pull request by okcoker**
This does a couple things:

- Installs a newer version of Linkify (which hasn't been released yet so I referenced the latest commit)
- Uses a <Link> tag for screenhole links
- Adds `nofollow` and `noopener` to external links (nofollow can be removed if this is not desired but noopener should be there)

fixes https://github.com/yothinko/screenhole/issues/47

### CODE REVIEW

**Comment by okcoker** [comment]
Woah, with the quickness

**Comment by pugson** [comment]
```
2:41:41 AM: Failed to compile.
2:41:41 AM: ./src/utils/Linkify.js
2:41:41 AM: Cannot find module: 'react-linkify'. Make sure this package is installed.
2:41:41 AM: You can install this package by running: yarn add react-linkify.
2:41:41 AM: error Command failed with exit code 1.
```

Dang, gotta fix this in build steps.

**Comment by okcoker** [comment]
Where can I see that? `yarn add react-linkify` would overwrite the newly commit-linked package.

**Comment by pugson** [comment]
That's our Netlify output. Easy fix, just gotta drop the `.git` from the URL.

**Comment by pugson** [comment]
I'm doing that on master since this has been merged already! Let me add deploy previews for GitHub.

**Comment by pugson** [comment]
@okcoker Turns out [this commit](https://github.com/tasti/react-linkify/commit/f1c6c8b5d5316cbe3c11cdf2c0611e3e91f1ea27) made the whole thing go nuts when building in Netlify. I rolled back to an older commit and everything works now.

**Comment by okcoker** [comment]
Ah okay that makes sense. `package.json` has the main file as `dist/Linkify` but that last commit removed the `dist` folder, presumably because when he publishes the npm module, it will include the dist folder within the package.

Not sure how that commit worked for me locally. I really only did this fer the buttcoinz anyway 😬

**Pull request merged**
